### ISSUE TITLE
Inifinite loop when extracting

### ISSUE THREAD

**Issue by nonunknown** [OpenDriver2/OpenDriver2Tools#3]
When extracting with the following command:

`DriverLevelTool.exe -format 2 -regformat 3 -textures 1 -explodetpages -models 1 -carmodels 1 -world 1 -lev DRIVER2/levels/CHICAGO.lev`

got this message infinitely:

```
Unknown polygons:
15 (sz=0), 31 (sz=0), 30 (sz=0), 14 (sz=0), 4 (sz=20), 26 (sz=0), 24 (sz=0),
```

It extracts models fine, but no texture is extracted:
![image](https://user-images.githubusercontent.com/58845030/103140720-d3751000-46c8-11eb-8557-eed10c52c11c.png)
![image](https://user-images.githubusercontent.com/58845030/103140724-da038780-46c8-11eb-96ed-6f54859f90cc.png)

**Comment by SoapyMan** [comment]
Try using build from appveyor instead, it should have been fixed.
